# Generated by Django 4.2.5 on 2023-10-13 12:55

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("Users", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="is_verified",
            field=models.BooleanField(auto_created=True, blank=True, default=False),
        ),
    ]
