# Generated by Django 4.2.5 on 2023-10-02 13:49

import Users.models
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("Users", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="cover_picture",
            field=models.ImageField(
                blank=True, null=True, upload_to=Users.models.user_directory_path
            ),
        ),
    ]
