# Generated by Django 4.2.5 on 2023-10-10 15:54

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("main", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="recipeimage",
            old_name="images",
            new_name="image",
        ),
    ]
